spring.application.name=login
#server.servlet.context-path=/api

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

server.error.include-message=always
server.error.include-binding-errors=always

jwt.expiration=${JWT_EXPIRATION}
jwt.secret=${JWT_SECRET}

spring.security.oauth2.client.registration.google.client-id=${CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=email,profile

notificationapi.secret=${NOTIFICATION_SECRET}
notificationapi.id=${NOTIFICATION_ID}
notificationapi.name=${NOTIFICATION_NAME}
notificationapi.app.base-url=${NOTIFICATION_BASE_URL}

token.email.validity=${TOKEN_EMAIL_VALIDITY}
token.password.validity=${TOKEN_PASSWORD_VALIDITY}
app.base-url=${APP_BASE}

spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true